replicaCount: 1

image:
  repository: docker.elastic.co/kibana/kibana
  tag: 6.4.3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  host: "kibana.example.com"

config:
  elasticsearch:
    host: 127.0.0.1
    port: 9200
    scheme: http
