apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "kibana.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: {{ .Values.service.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "kibana.fullname" . }}
          servicePort: {{ .Values.service.port }}
